name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.5

    - name: Install TinyGo 0.20.0
      run: |
        wget https://github.com/tinygo-org/tinygo/releases/download/v0.20.0/tinygo_0.20.0_amd64.deb
        sudo dpkg -i tinygo_0.20.0_amd64.deb

    - name: Build
      run: make build

    - name: Run tests
      run: make test
