name: release
on:
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  BINDLE_URL: <%= serverUrl %>
  HIPPO_URL: <%= hippoUrl %>

jobs:
  publish:
    strategy:
      matrix:
        wasi_sdk_version:
        - major: 11
          minor: 0

    name: Build release assets
    runs-on: golang:1.17

    steps:
    - uses: actions/checkout@v2

    - name: Set the release version (tag)
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash
      run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Set the release version (main)
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: echo "RELEASE_VERSION=canary" >> $GITHUB_ENV

    - name: Install TinyGo 0.21.0
      run: |
        wget https://github.com/tinygo-org/tinygo/releases/download/v0.21.0/tinygo_0.21.0_amd64.deb
        sudo dpkg -i tinygo_0.21.0_amd64.deb

    - name: Build release
      run: make build

    - name: Install Hippo CLI
      run: |
        mkdir -p tools/tmp
        wget https://github.com/deislabs/hippo-cli/releases/download/v0.9.0/hippo-v0.9.0-linux-amd64.tar.gz -q -O ./tools/tmp/hippo.tar.gz
        tar xf ./tools/tmp/hippo.tar.gz -C ./tools

    - name: Publish bindle (tagged)
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        HIPPO_USERNAME: ${{ secrets.HIPPO_USERNAME }}
        HIPPO_PASSWORD: ${{ secrets.HIPPO_PASSWORD }}
        BINDLE_USERNAME: ${{ secrets.BINDLE_USERNAME }}
        BINDLE_PASSWORD: ${{ secrets.BINDLE_PASSWORD }}
      run: ./tools/hippo push . -v production -o message

    - name: Publish bindle (main)
      if: github.ref == 'refs/heads/main'
      env:
        HIPPO_USERNAME: ${{ secrets.HIPPO_USERNAME }}
        HIPPO_PASSWORD: ${{ secrets.HIPPO_PASSWORD }}
        BINDLE_USERNAME: ${{ secrets.BINDLE_USERNAME }}
        BINDLE_PASSWORD: ${{ secrets.BINDLE_PASSWORD }}
      run: USER=canary ./tools/hippo push . -o message
