name: release
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    name: Build release assets
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set the release version (tag)
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash
      run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Set the release version (main)
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: echo "RELEASE_VERSION=canary" >> $GITHUB_ENV

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.5

    - name: Install TinyGo 0.20.0
      run: |
        wget https://github.com/tinygo-org/tinygo/releases/download/v0.20.0/tinygo_0.20.0_amd64.deb
        sudo dpkg -i tinygo_0.20.0_amd64.deb

    - name: Build release
      run: make build

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: <%= moduleName %>.wasm
        path: ./<%= moduleName %>.wasm

  publish:
    name: Push released module to OCI registry
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Install wasm-to-oci
      run: |
        mkdir tools
        wget https://github.com/engineerd/wasm-to-oci/releases/download/v0.1.1/linux-amd64-wasm-to-oci -q -O ./tools/wasm-to-oci
        chmod +x ./tools/wasm-to-oci

    - name: Set the release version
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Set the release version
      if: github.ref == 'refs/heads/main'
      run: echo "RELEASE_VERSION=canary" >> $GITHUB_ENV

    - name: Download release assets
      uses: actions/download-artifact@v1
      with:
        name: <%= moduleName %>.wasm
        path: ./assets

    # TODO: FILL IN THE << ... >> bit below according to the chosen OCI-compliant registry

    # - name: Log into registry
    #   run: << your docker login equivalent here >>

    # - name: Publish to registry
    #   run: ./tools/wasm-to-oci push ./assets/<%= moduleName %>.wasm << your OCI reference here e.g. myname.myprovider.io/<%= moduleName %>:${RELEASE_VERSION} >>
